/*
 * Acquisto.java
 *
 * Created on 13-giu-2009, 16.49.39
 */

package it.unina.scienzeinfo.labdb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Gruppo 3
 */
public class Acquisto extends DBFrame {
 int id_fattura;
    /* Invoca il costruttore di Acquisto*/
    public Acquisto(int id_fattura) {
                initComponents();
        this.id_fattura=id_fattura;
        ImpostaPosizioneFinestra();//Gestione posizione della finestra
        setModalita(SELL); //Imposta la finestra per l'inserimento
        setNomeTabella("acquisto");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPrezzo = new javax.swing.JLabel();
        jQuantita = new javax.swing.JLabel();
        jProdotto = new javax.swing.JLabel();
        tProdotto = new javax.swing.JTextField();
        tQuantita = new javax.swing.JTextField();
        tPrezzo = new javax.swing.JTextField();
        bAggiungi = new javax.swing.JButton();
        bElimina = new javax.swing.JButton();
        bModifica = new javax.swing.JButton();
        bChiudi = new javax.swing.JButton();
        bAnnulla = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Acquisto");

        jPanel1.setPreferredSize(new java.awt.Dimension(811, 423));

        jPrezzo.setText("Costo*");

        jQuantita.setText("Quantità*");

        jProdotto.setText("Prodotto*");

        tProdotto.setToolTipText("Inserire un codice prodotto esistente");

        tQuantita.setText("1");
        tQuantita.setToolTipText("Intero di 3 cirfe");

        tPrezzo.setToolTipText("Esempio 123.12");

        bAggiungi.setText("Aggiungi Prodotto");
        bAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAggiungiActionPerformed(evt);
            }
        });

        bElimina.setText("Elimina Prodotto");
        bElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminaActionPerformed(evt);
            }
        });

        bModifica.setText("Modifica Prodotto");
        bModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificaActionPerformed(evt);
            }
        });

        bChiudi.setText("Chiudi Fattura");
        bChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChiudiActionPerformed(evt);
            }
        });

        bAnnulla.setText("Annulla Fattura");
        bAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnullaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("Aggiungi prodotto: Si aggiunge un prodotto alla fattura\n\nElimina Prodotto: Si elimina un prodotto già inserito \n\nModifica Quantità: Si modifica la quantità di un \nprodotto precedentemente inserito\n\nAnnulla Fattura: Si elimina la fattura e tutte le sue voci\n\nChiudi Fattura: Termina la fase di inserimento \ndei prodotti, una volta premuto il tasto non sarà \npiù possibile modificare la fattura");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jProdotto)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPrezzo)
                                    .addComponent(jQuantita)))
                            .addComponent(bAggiungi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(bElimina)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bModifica))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tPrezzo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tQuantita, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tProdotto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bChiudi)
                        .addGap(254, 254, 254)
                        .addComponent(bAnnulla)))
                .addGap(447, 447, 447))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProdotto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tQuantita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jQuantita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tPrezzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPrezzo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bModifica)
                    .addComponent(bElimina)
                    .addComponent(bAggiungi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bChiudi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAnnulla))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Eliminazione di un prodotto da una fattura
    private void bEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminaActionPerformed
        String controllo,controllo2;
        controllo=Database.leggiValore("select nvl(count(*),0) from "+Database.schema+".Acquisto where id_fattura="+id_fattura).toString();
        SendQuery("delete from "+ Database.schema+".acquisto where id_prodotto="+tProdotto.getText()+" and id_fattura="+id_fattura);
        controllo2=Database.leggiValore("select nvl(count(*),0) from "+Database.schema+".Acquisto where id_fattura="+id_fattura).toString();
        if(!controllo.matches(controllo2))
        {
           JOptionPane.showMessageDialog(this, "Prodotto Eliminato Correttamente", "JetMarket", JOptionPane.INFORMATION_MESSAGE);
        }
        else
           JOptionPane.showMessageDialog(this, "Prodotto non eliminato perchè non presente nella fattura", "JetMarket", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bEliminaActionPerformed

    //Aggiunta di un prodotto in una fattura
    private void bAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAggiungiActionPerformed
        String controllo,controllo2;
        controllo=Database.leggiValore("select nvl(count(*),0) from "+Database.schema+".Acquisto where id_fattura="+id_fattura).toString();
        Salva(evt);
        controllo2=Database.leggiValore("select nvl(count(*),0) from "+Database.schema+".Acquisto where id_fattura="+id_fattura).toString();

        if(!controllo.matches(controllo2))
        {
           JOptionPane.showMessageDialog(this, "Prodotto Inserito Correttamente", "JetMarket", JOptionPane.INFORMATION_MESSAGE);
        }
}//GEN-LAST:event_bAggiungiActionPerformed
    //Chiusura della finestra acquisto, da questo momnto non sarà possibile rieditare lo scontrino
    private void bChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChiudiActionPerformed
       dispose();
    }//GEN-LAST:event_bChiudiActionPerformed
    //Annullamento dello fattura e cancellazione della stessa
    private void bAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnullaActionPerformed
        SendQuery("delete from "+ Database.schema+".acquisto where id_fattura="+id_fattura);
        SendQuery("delete from "+ Database.schema+".fattura where codice="+id_fattura);
        dispose();
    }//GEN-LAST:event_bAnnullaActionPerformed

    //Modifica la quantità di un prodotto
    private void bModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificaActionPerformed
        int Quantita,Prodotto;
        float Prezzo;
        String controllo;
        float controllo2;
        if(ControllaInput(3,tQuantita.getText(),"N1toSize") && 
                ControllaInput(5,tProdotto.getText(),"N1toSize") &&
                ControllaInput(5,tPrezzo.getText(),"F5.2"))
        {
           Quantita=Integer.valueOf(tQuantita.getText()).intValue();
           Prodotto=Integer.valueOf(tProdotto.getText()).intValue();
           Prezzo=Float.valueOf(tPrezzo.getText()).floatValue();
           SendQuery("update "+ Database.schema+".acquisto set quantita="+Quantita+", prezzo="+Prezzo+" where id_fattura="+id_fattura +" and id_prodotto="+Prodotto);
           controllo=Database.leggiValore("select quantita from "+Database.schema+".acquisto where id_fattura="+id_fattura +" and id_prodotto="+Prodotto).toString();
           controllo2=Float.valueOf(Database.leggiValore("select prezzo from "+Database.schema+".acquisto where id_fattura="+id_fattura +" and id_prodotto="+Prodotto).toString()).floatValue();
           if(controllo.matches(Integer.toString(Quantita)) && controllo2==Prezzo)
           {
               JOptionPane.showMessageDialog(this, "Dati modificati Correttamente", "JetMarket", JOptionPane.INFORMATION_MESSAGE);
           }
           else
               JOptionPane.showMessageDialog(this, "Dati non modificatiCorrettamente", "JetMarket", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bModificaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAggiungi;
    private javax.swing.JButton bAnnulla;
    private javax.swing.JButton bChiudi;
    private javax.swing.JButton bElimina;
    private javax.swing.JButton bModifica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jPrezzo;
    private javax.swing.JLabel jProdotto;
    private javax.swing.JLabel jQuantita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField tPrezzo;
    private javax.swing.JTextField tProdotto;
    private javax.swing.JTextField tQuantita;
    // End of variables declaration//GEN-END:variables

    @Override
    protected PreparedStatement getComandoInserimento(Connection c) throws SQLException {
         String query;
        PreparedStatement st = null;
        //Controllo del corretto inserimento dei dati
        if(ControllaInput(5,tProdotto.getText(),"N1toSize") &&
                ControllaInput(3,tQuantita.getText(),"N1toSize") &&
                ControllaInput(0,tPrezzo.getText(),"F5.2"))
        {
           query="insert into "+Database.schema+".Acquisto(id_prodotto,quantita,prezzo,id_fattura) values(?,?,?,?)";
           st=c.prepareStatement(query);
           st.setInt(4,id_fattura);
           st.setInt(1,Integer.valueOf(tProdotto.getText()).intValue());
           st.setInt(2,Integer.valueOf(tQuantita.getText()).intValue());
           st.setFloat(3,Float.valueOf(tPrezzo.getText()).floatValue());
        }
        else
        {
           MostraMessaggioErrore("Uno dei seguenti campi è errato: \n -Prodotto \n -Quantita  \n -Prezzo");
        }
        return st;
    }

    @Override
    protected PreparedStatement getComandoAggiornamento(Connection c) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
