/*
 * Login.java
 *
 * Created on 23 aprile 2009, 23.11
 */

package it.unina.scienzeinfo.labdb;
import java.awt.Dimension;
import java.sql.*;
import javax.swing.*;

/**
 * Finestra di dialogo per impostare  i parametri di connessione al DataBase.
 * @author  Gruppo 3
 */
public class Login extends javax.swing.JDialog {
    
    public static final int PREMUTO_ANNULLA = 0;
    public static final int PREMUTO_LOGIN = 1;
    /** Crea un nuovo form Login */
    public Login(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Gestione posizione della finestra
        Dimension screen=getToolkit().getScreenSize();
        int Largh=screen.width;
        int Alt=screen.height;
        int posX=(Largh - 416)/2;
        int posY=(Alt - 329)/2;
        setLocation(posX,posY);
    }
    private int bottonePremuto;

    //Ritorna il valore di Bottone
    public int getBottonePremuto() {
        return bottonePremuto;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bLogin = new javax.swing.JButton();
        bAnnulla = new javax.swing.JButton();
        jLogin = new javax.swing.JLabel();
        jHost = new javax.swing.JLabel();
        jPorta = new javax.swing.JLabel();
        jServizio = new javax.swing.JLabel();
        jSchema = new javax.swing.JLabel();
        tSchema = new javax.swing.JTextField();
        tHost = new javax.swing.JTextField();
        tServizio = new javax.swing.JTextField();
        tPorta = new javax.swing.JTextField();
        jUtente = new javax.swing.JLabel();
        jPassword = new javax.swing.JLabel();
        tUtente = new javax.swing.JTextField();
        tPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        bLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/scienzeinfo/labdb/Immagini/connect.png"))); // NOI18N
        bLogin.setMnemonic('L');
        bLogin.setText("Login");
        bLogin.setToolTipText("Clicca per entrare");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });

        bAnnulla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/it/unina/scienzeinfo/labdb/Immagini/cancel.png"))); // NOI18N
        bAnnulla.setMnemonic('A');
        bAnnulla.setText("Annulla");
        bAnnulla.setToolTipText("Clicca per uscire");
        bAnnulla.setPreferredSize(new java.awt.Dimension(67, 28));
        bAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnullaActionPerformed(evt);
            }
        });

        jLogin.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLogin.setText("JetMarket Login");
        jLogin.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jHost.setText("Host");

        jPorta.setText("Porta");

        jServizio.setText("Servizio");

        jSchema.setText("Schema");

        tSchema.setBackground(new java.awt.Color(204, 204, 204));
        tSchema.setText("user");

        tHost.setBackground(new java.awt.Color(204, 204, 204));
        tHost.setText("localhost");

        tServizio.setBackground(new java.awt.Color(204, 204, 204));
        tServizio.setText("XE");

        tPorta.setBackground(new java.awt.Color(204, 204, 204));
        tPorta.setText("1521");

        jUtente.setText("Utente");

        jPassword.setText("Password");

        tUtente.setText("user");

        tPassword.setFont(new java.awt.Font("Tahoma", 0, 10));
        tPassword.setText("user");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(131, 131, 131)
                .add(jLogin)
                .addContainerGap(164, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPorta)
                    .add(jHost)
                    .add(jServizio)
                    .add(jSchema)
                    .add(jUtente)
                    .add(jPassword))
                .add(1, 1, 1)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(bLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 94, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(bAnnulla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(tPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tUtente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 282, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 231, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tServizio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 71, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tSchema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        layout.linkSize(new java.awt.Component[] {tHost, tPassword, tPorta, tSchema, tServizio, tUtente}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLogin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jHost)
                    .add(tHost, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tPorta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPorta))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tServizio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jServizio))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tSchema, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jSchema))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tUtente, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jUtente))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(tPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPassword))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(bAnnulla, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bLogin))
                .add(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        //Azione sul tasto Annulla
    private void bAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnullaActionPerformed
        bottonePremuto=PREMUTO_ANNULLA;
        dispose();
    }//GEN-LAST:event_bAnnullaActionPerformed
    //Azione sul tasto Login
    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        //Acquisizione dei campi per la connessione al database
        Database.host=tHost.getText();
        Database.porta=tPorta.getText();
        Database.schema=tSchema.getText();
        Database.servizio=tServizio.getText();
        Database.user=tUtente.getText();
        Database.password=new String(tPassword.getPassword());
        try {
            //Stabilisce la connessione di default
            Database.setDefaultConnection(Database.nuovaConnessione());
            //Imposta il bottone su Login
            bottonePremuto=PREMUTO_LOGIN;
            dispose();
        } catch (SQLException e) {
            //Finestra di dialogo in caso di inserimento credenziali errate
            JOptionPane.showMessageDialog(this, "Credenziali di connessione errati", "Errore", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bLoginActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnnulla;
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel jHost;
    private javax.swing.JLabel jLogin;
    private javax.swing.JLabel jPassword;
    private javax.swing.JLabel jPorta;
    private javax.swing.JLabel jSchema;
    private javax.swing.JLabel jServizio;
    private javax.swing.JLabel jUtente;
    private javax.swing.JTextField tHost;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tPorta;
    private javax.swing.JTextField tSchema;
    private javax.swing.JTextField tServizio;
    private javax.swing.JTextField tUtente;
    // End of variables declaration//GEN-END:variables
    
}
