/*
 * Vendita.java
 *
 * Created on 13-giu-2009, 10.08.19
 */

package it.unina.scienzeinfo.labdb;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Gruppo 3
 */
public class Vendita extends DBFrame {
   int id_scontrino;
    /* Invoca il costruttore di Vendita*/
    public Vendita(int id_scontrino) {
        initComponents();
        this.id_scontrino=id_scontrino;
        ImpostaPosizioneFinestra();//Gestione posizione della finestra
        setModalita(SELL); //Imposta la finestra per l'inserimento
        setNomeTabella("vendita");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProdotto = new javax.swing.JLabel();
        jQuantita = new javax.swing.JLabel();
        bAnnulla = new javax.swing.JButton();
        bAggiungi = new javax.swing.JButton();
        bElimina = new javax.swing.JButton();
        tQuantita = new javax.swing.JTextField();
        tProdotto = new javax.swing.JTextField();
        bChiudi = new javax.swing.JButton();
        bModifica = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vendita");

        jProdotto.setText("Prodotto*");

        jQuantita.setText("Quantità*");

        bAnnulla.setText("Annulla Scontrino");
        bAnnulla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnullaActionPerformed(evt);
            }
        });

        bAggiungi.setText("Aggiungi Prodotto");
        bAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAggiungiActionPerformed(evt);
            }
        });

        bElimina.setText("Elimina Prodotto");
        bElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminaActionPerformed(evt);
            }
        });

        tQuantita.setText("1");
        tQuantita.setToolTipText("Intero di 3 cifre");

        tProdotto.setToolTipText("Inserire un codice prodotto esistente");

        bChiudi.setText("Chiudi Scontrino");
        bChiudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChiudiActionPerformed(evt);
            }
        });

        bModifica.setText("Modifica Quantita ");
        bModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bModificaActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jTextArea1.setText("Aggiungi prodotto: Si aggiunge un prodotto allo scontrino\n\nElimina Prodotto: Si elimina un prodotto già inserito\n \nModifica Quantità: Si modifica la quantità di un prodotto \nprecedentemente inserito\n\nAnnulla Scontrino: Si elimina lo scontrino e tutte le sue voci\n\nChiudi Scontrino: Termina la fase di inserimento dei prodotti, \nuna volta premuto il tasto non sarà più possibile modificare \nlo scontrino");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProdotto, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jQuantita, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tQuantita, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tProdotto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(bAnnulla)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bChiudi))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(bAggiungi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(bElimina)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bModifica))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProdotto)
                    .addComponent(tProdotto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jQuantita)
                    .addComponent(tQuantita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAggiungi)
                    .addComponent(bElimina)
                    .addComponent(bModifica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAnnulla)
                    .addComponent(bChiudi))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Eliminazione di un prodotto da uno scontrino
    private void bEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminaActionPerformed
        String controllo,controllo2;
        controllo=Database.leggiValore("select nvl(count(*),0) from "+Database.schema+".Vendita where id_scontrino="+id_scontrino).toString();
        SendQuery("delete from "+ Database.schema+".vendita where prodotto="+tProdotto.getText()+"and id_scontrino="+id_scontrino);
        controllo2=Database.leggiValore("select nvl(count(*),0) from "+Database.schema+".Vendita where id_scontrino="+id_scontrino).toString();
        if(!controllo.matches(controllo2))
        {
           JOptionPane.showMessageDialog(this, "Prodotto Eliminato Correttamente", "JetMarket", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        JOptionPane.showMessageDialog(this, "Prodotto non eliminato perchè non presente nello scontrino", "JetMarket", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bEliminaActionPerformed

    //Aggiunta di un prodotto ad uno scontrino
    private void bAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAggiungiActionPerformed
        String controllo,controllo2;
        controllo=Database.leggiValore("select nvl(count(*),0) from "+Database.schema+".Vendita where id_scontrino="+id_scontrino).toString();
        Salva(evt);
        controllo2=Database.leggiValore("select nvl(count(*),0) from "+Database.schema+".Vendita where id_scontrino="+id_scontrino).toString();
        
        if(!controllo.matches(controllo2))
        {
           JOptionPane.showMessageDialog(this, "Prodotto Inserito Correttamente", "JetMarket", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bAggiungiActionPerformed

    //Chiusura della finestra vendita, da questo momnto non sarà possibile rieditare lo scontrino
    private void bChiudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChiudiActionPerformed
        dispose();
    }//GEN-LAST:event_bChiudiActionPerformed
    //Annullamento dello scontrino e cancellazione dello stesso
    private void bAnnullaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnullaActionPerformed
        SendQuery("delete from "+ Database.schema+".vendita where id_scontrino="+id_scontrino);
        SendQuery("delete from "+ Database.schema+".scontrino where codice="+id_scontrino);
        dispose();
    }//GEN-LAST:event_bAnnullaActionPerformed

    //Modifica la quantità di un prodotto
    private void bModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bModificaActionPerformed
        int Quantita,Prodotto;
        String controllo;
        if(ControllaInput(3,tQuantita.getText(),"N1toSize") && ControllaInput(5,tProdotto.getText(),"N1toSize"))
        {
           Quantita=Integer.valueOf(tQuantita.getText()).intValue();
           Prodotto=Integer.valueOf(tProdotto.getText()).intValue();
           SendQuery("update "+ Database.schema+".vendita set quantita="+Quantita+" where id_scontrino="+id_scontrino +" and prodotto="+Prodotto);
           controllo=Database.leggiValore("select quantita from "+Database.schema+".Vendita where id_scontrino="+id_scontrino +" and prodotto="+Prodotto).toString();
           if(controllo.matches(Integer.toString(Quantita)))
           {
               JOptionPane.showMessageDialog(this, "Quantità Modificata Correttamente", "JetMarket", JOptionPane.INFORMATION_MESSAGE);
           }
           else
               JOptionPane.showMessageDialog(this, "Quantità non Modificata Correttamente", "JetMarket", JOptionPane.ERROR_MESSAGE);
        }
}//GEN-LAST:event_bModificaActionPerformed

    @Override
    /* Genera ed esegue la query per l'inserimento di un dato*/
    protected PreparedStatement getComandoInserimento(Connection c) throws SQLException {
         String query;
        PreparedStatement st = null;
        //Controllo del corretto inserimento dei dati
        if(ControllaInput(5,tProdotto.getText(),"N1toSize") &&
                ControllaInput(3,tQuantita.getText(),"N1toSize"))
        {
           query="insert into "+Database.schema+".Vendita(prodotto,quantita,id_Scontrino) values(?,?,?)";
           st=c.prepareStatement(query);
           st.setInt(3,id_scontrino);
           st.setInt(1,Integer.valueOf(tProdotto.getText()).intValue());
           st.setInt(2,Integer.valueOf(tQuantita.getText()).intValue());
        }
        else
        {
           MostraMessaggioErrore("Uno dei seguenti campi sono errati: \n -Prodotto \n -Quantita");
        }
        return st;
    }

    @Override
    /* Genera ed esegue la query per la modifica di un dato*/
    protected PreparedStatement getComandoAggiornamento(Connection c) throws SQLException {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAggiungi;
    private javax.swing.JButton bAnnulla;
    private javax.swing.JButton bChiudi;
    private javax.swing.JButton bElimina;
    private javax.swing.JButton bModifica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jProdotto;
    private javax.swing.JLabel jQuantita;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField tProdotto;
    private javax.swing.JTextField tQuantita;
    // End of variables declaration//GEN-END:variables

}
